### ISSUE TITLE
`profile` component is missing a non-canonical `properties` form

### ISSUE THREAD

**Issue by BemusedLeader10** [SpyglassMC/vanilla-mcdoc#38]
Featured is a snipped from a loot table:
![image](https://github.com/user-attachments/assets/3522e839-3554-4b69-b85f-867759a46fa7)

**Comment by MulverineX** [comment]
Fixed by https://github.com/SpyglassMC/vanilla-mcdoc/commit/bbc08029a5bbf9ba57adfd9fd84b1859d835dc74
