### ISSUE TITLE
`trial_spawner` block entity missing several fields

### ISSUE THREAD

**Issue by devvoid** [SpyglassMC/vanilla-mcdoc#39]
When configuring a trial spawner via a processor list, only a few of its config properties are picked up by Spyglass, the rest being reported as unrecognized. Affected properties are:
- `spawn_range`
- `total_mobs`
- `total_mobs_added_per_player`
- `loot_tables_to_eject` (Only for the normal config though, it recognizes this one fine on the ominous config)
- `items_to_drop_when_ominous`

Here's an example loot table that demonstrates the issue: [spawner_generic.json](https://github.com/user-attachments/files/16567868/spawner_generic.json). This should show that the properties above are marked as unrecognized.

Version: 4.2.0

**Comment by jacobsjo** [comment]
Its missing even more fields: `required_player_range`, `target_cooldown_length`, and all the state-tracking values (see https://minecraft.wiki/w/Trial_Spawner#Block_data)
