### ISSUE TITLE
Non-canonical form for entity_data

### ISSUE THREAD

**Issue by Kesuaheli** [SpyglassMC/vanilla-mcdoc#47]
Spyglass doesn't like this
![image-1.png](https://github.com/user-attachments/assets/0264e5b0-3503-4a81-b83f-28605eadf44c)
and wants this
![image-2.png](https://github.com/user-attachments/assets/d250c553-d7e1-4b90-9462-a738cf18cef5)

Found this, where it just takes the entity data.
https://github.com/SpyglassMC/vanilla-mcdoc/blob/33cf80844b06dbe2a27d133f16596daa2b00f9cb/java/server/world/item/spawn_item.mcdoc#L1-L4

Minecraft accepts both the SNBT string and the JSON Object. However, I like the string more because I feel like it's more accurate and less prone to conversion errors (especially number data type conversion).

**Comment by NeunEinser** [comment]
Can you use a string when e.g. specifying it in a give command?

Changing the definition you linked would imply it's possible anywhere.
