### ISSUE TITLE
How do I use vanilla-mcdoc in my js/ts project?

### ISSUE THREAD

**Issue by karakufire** [SpyglassMC/vanilla-mcdoc#48]
I found this project distributed on npm, but I cannot search out how to use it in my javascript/typescript project powered by Node.js or Deno.
Perhaps the main use cases of vanilla-mcdoc are Spyglass a VSCode addon, or Datapack Generator, but it is constructed by huge sourcecodes so it's hard to find the use cases.
Therefore I would appreciate if you could tell me the examples of using or how to use this in individual local projects after it's imported on npm.

**Comment by misode** [comment]
This project itself is not published on npm, this repository only contains the mcdoc schemas. We have a main monorepo [SpyglassMC/Spyglass](https://github.com/SpyglassMC/Spyglass) that has multiple packages published to npm which are responsible for downloading this repo, parsing, and handling these mcdoc files.

Right now there are not many examples using mcdoc outside of the spyglass vscode extension. If you have a specific need, I'd be happy to help you though!

**Comment by karakufire** [comment]
Then is it better that I ask in Spyglass repository how to use the library distributed by npm? Because I thought the issues of Spyglass should be relating to VSCode extensions.

**Comment by misode** [comment]
Yes, the Spyglass repo seems more appropriate. Alternatively, you could also ask in our discord, which is probably easier to communicate quickly: https://discord.gg/EbdseuS

**Comment by karakufire** [comment]
I understand. Thank you for the consultation. I'd like to ask them again on discord.
