### ISSUE TITLE
Rework how entity memory module works

### ISSUE THREAD

**Issue by misode** [SpyglassMC/vanilla-mcdoc#8]
Currently the different memory module types are all dispatched in a single file and it isn't clear what mobs use what memory modules. This requires some code analysis but should be much more useful since it never makes sense using a memory module not used by a mob.

**Comment by misode** [comment]
How was this fixed @MulverineX?

**Comment by MulverineX** [comment]
https://github.com/SpyglassMC/vanilla-mcdoc/commit/20e5d380875923cde866495c1b6d6fd717d1e178

**Comment by MulverineX** [comment]
@misode https://github.com/SpyglassMC/vanilla-mcdoc/commit/20e5d380875923cde866495c1b6d6fd717d1e178
